name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - ChetanBhasin

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: impact
    attributes:
      label: Impact on Performance
      description: How might this feature impact performance?
      options:
        - No performance impact expected
        - Minor performance improvement
        - Significant performance improvement
        - Potential performance regression
        - Unknown/needs investigation
    validations:
      required: true

  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility
      description: Check all that apply
      options:
        - label: This feature should work on all supported platforms
        - label: This feature is Linux/io_uring specific
        - label: This feature affects the public API
        - label: This feature is backward compatible

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ChetanBhasin/websockets-monoio/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true